# -*- coding: utf-8 -*-
"""Tas_Kagit_Makas_Oyunu_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LX9jCk7zoa7gjtrtOAzCR87FLNG03Z1N
"""

import random

print("--------TAŞ KAĞIT MAKAS OYUNU--------------")
def tas_kagit_makas():
    secenekler = ["tas", "kağıt", "makas"]
    bilgisayar_secimi = random.choice(secenekler)

    sec = input("Siz:")
    print(f"Bilgisayar:{bilgisayar_secimi}")

    if (bilgisayar_secimi == sec):
        print("Berabere!")

    elif (bilgisayar_secimi == "tas" and sec == "kağıt"):
        print("Tebrikler kazandınız!")

    elif (bilgisayar_secimi == "tas" and sec == "makas"):
        print("Bilgisayar kazandı!")

    elif (bilgisayar_secimi == "kağıt" and sec == "tas"):
        print("Bilgisayar kazandı!")

    elif (bilgisayar_secimi == "kağıt" and sec == "makas"):
        print("Tebrikler kazandınız!!")

    elif (bilgisayar_secimi == "makas" and sec == "tas"):
        print("Tebrikler kazandınız!!")

    elif (bilgisayar_secimi == "makas" and sec == "kağıt"):
        print("Bilgisayar kazandı!")

tas_kagit_makas()

